applications:
  - name: django-app
    namespace: ${destination_ns}
    project: default
    source:
      repoURL: ${app_repo_url}
      path: ${app_path}
      targetRevision: ${app_revision}
      helm:
        # якщо список порожній — отримаємо [] і шаблон просто нічого не підставить
        valueFiles: ${app_value_files_yaml}
    destination:
      server: https://kubernetes.default.svc
      namespace: ${destination_ns}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

# Список репозиторіїв для реєстрації в Argo CD (як Secrets)
repositories: ${repositories_yaml}
repoConfig:
  insecure: ${repo_insecure}
  enableLfs: ${repo_enable_lfs}
