controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts-jdk21

  admin:
    createSecret: true
    username: admin
    password: ""

  serviceType: ClusterIP
  servicePort: 80

  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi

  installPlugins:
    - ansicolor:1.0.4
    - timestamper:1.26
    - configuration-as-code
    - job-dsl
    - git
    - git-client
    - ssh-credentials
    - workflow-aggregator
    - ssh-agent

  # даємо Дженкінсу час на перший старт
  startupProbe:
    httpGet:
      path: /login
      port: http
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 90   # ~15 хв максимум

  livenessProbe:
    httpGet:
      path: /login
      port: http
    initialDelaySeconds: 900
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

  readinessProbe:
    httpGet:
      path: /login
      port: http
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  containerEnv:
    - name: GITOPS_SSH_PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: gitops-ssh
          key: ssh-privatekey

  JCasC:
    configScripts:
      gitops-credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - basicSSHUserPrivateKey:
                      scope: GLOBAL
                      id: "gitops-ssh"
                      username: "git"
                      description: "GitHub deploy key for GitOps push"
                      privateKeySource:
                        directEntry:
                          privateKey: "${GITOPS_SSH_PRIVATE_KEY}"

      pipelines: |
        jobs:
          - script: >
              pipelines: |
        jobs:
          - script: >
              pipelineJob('django-app-ci') {
                description('CI/CD for Django app: build & push image to ECR, bump Helm values, push to repo')
                definition {
                  cpsScm {
                    lightweight(true)
                    scm {
                      git {
                        remote {
                          url('https://github.com/DanSport/DevOps.git')   // ← HTTPS!
                        }
                        branches('*/lesson-8-9')
                      }
                    }
                    scriptPath('Progect/Jenkinsfile')
                  }
                }
                triggers { scm('H/2 * * * *') }
              }
              
rbac:
  create: true

serviceAccount:
  create: false
  name: jenkins-sa

git-host-key-verification: |
  unclassified:
    gitHostKeyVerificationConfiguration:
      sshHostKeyVerificationStrategy: "Accept first connection"


