controller:
  admin:
    createSecret: true
    username: admin
    password: ""

  serviceType: ClusterIP
  servicePort: 80

  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi
  installPlugins:
    - ansicolor:1.0.4
    - timestamper:1.26
rbac:
  create: true

serviceAccount:
  create: false
  name: jenkins-sa

persistence:
  enabled: true
  storageClass: gp3
  size: 10Gi
