controller:
  admin:
    createSecret: true
    username: admin
    password: ""

  serviceType: ClusterIP
  servicePort: 80

  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi

rbac:
  create: true

serviceAccount:
  create: false
  name: jenkins-sa

