image:
  repository: 785434010839.dkr.ecr.us-east-1.amazonaws.com/lesson-7-ecr
  tag: "v3-app"
  pullPolicy: Always

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  env:
    DJANGO_STATIC_ROOT: "/var/www/static"
env:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppass                # у проді винести в Secret
  POSTGRES_HOST: postgres.default.svc.cluster.local
  POSTGRES_PORT: "5432"

  DJANGO_DEBUG: "0"
  DJANGO_SECRET_KEY: "insecure-dev-key"    # у проді винести в Secret
  DJANGO_ALLOWED_HOSTS: "*"

  # нове — куди складати статику
  DJANGO_STATIC_ROOT: "/var/www/static"

health:
  path: /admin/login/
  readinessInitialDelay: 5
  readinessPeriod: 5
  livenessInitialDelay: 20
  livenessPeriod: 10
