image:
  repository: 785434010839.dkr.ecr.us-east-1.amazonaws.com/lesson-7-ecr
  tag: build-17
  pullPolicy: Always

replicaCount: 2

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "*"

  # Для Django (settings.py зазвичай читає DB_*)
  DB_NAME: "appdb"
  DB_USER: "appuser"
  DB_HOST: "db"
  DB_PORT: "5432"

  # Для init/wait-for-db та postgres-контейнера (читають POSTGRES_*)
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "appuser"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

  DJANGO_STATIC_ROOT: "/var/www/static"
  
health:
  path: /admin/login/
  readinessInitialDelay: 5
  readinessPeriod: 5
  livenessInitialDelay: 20
  livenessPeriod: 10

envFrom: {} 

strategy:          
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 1
