apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
{{- if .Values.env }}
{{- range $k, $v := .Values.env }}
  {{ $k }}: "{{ $v }}"
{{- end }}
{{- else }}
  DJANGO_ALLOWED_HOSTS: "*"
{{- end }}
