apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "django-app.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
