apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django-app-svc
  labels:
    app: django-app
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
    app: django-app
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
